<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bip2"
    nsURI="http://bip2/1.0" nsPrefix="bip2">
  <eClassifiers xsi:type="ecore:EClass" name="PlaceHolder" abstract="true"/>
  <eSubpackages name="ujf" nsURI="http://bip2/ujf/1.0" nsPrefix="bip2.ujf">
    <eClassifiers xsi:type="ecore:EClass" name="PlaceHolder"/>
    <eSubpackages name="verimag" nsURI="http://bip2/ujf/verimag/1.0" nsPrefix="bip2.ujf.verimag">
      <eClassifiers xsi:type="ecore:EClass" name="PlaceHolder"/>
      <eSubpackages name="bip" nsURI="http://bip2/ujf/verimag/bip/1.0" nsPrefix="bip2.ujf.verimag.bip">
        <eClassifiers xsi:type="ecore:EClass" name="PlaceHolder"/>
        <eSubpackages name="types" nsURI="http://bip2/ujf/verimag/bip/types/1.0" nsPrefix="bip2.ujf.verimag.bip.types">
          <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eOperations name="isKindOf" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
              <eParameters name="type" eType="#//ujf/verimag/bip/types/Type"/>
            </eOperations>
            <eOperations name="isSubTypeOf" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
              <eParameters name="type" eType="#//ujf/verimag/bip/types/Type"/>
            </eOperations>
            <eOperations name="hasCastFor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
              <eParameters name="type" eType="#//ujf/verimag/bip/types/Type"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="native" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
                defaultValueLiteral="false"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
                eType="#//ujf/verimag/bip/types/Type"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="castableTypes"
                upperBound="-1" eType="#//ujf/verimag/bip/types/Type"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BipType" abstract="true" interface="true"
              eSuperTypes="#//ujf/verimag/bip/types/Type"/>
          <eClassifiers xsi:type="ecore:EClass" name="ComponentType" abstract="true"
              interface="true" eSuperTypes="#//ujf/verimag/bip/types/BipType">
            <eOperations name="getExportedPortDeclaration" eType="#//ujf/verimag/bip/port/PortDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getExportedDataDeclaration" eType="#//ujf/verimag/bip/data/DataDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getDataParameterDeclaration" eType="#//ujf/verimag/bip/component/ComponentDataParameterDeclaration">
              <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportedPortDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/port/PortDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportedDataDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataParameterDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/ComponentDataParameterDeclaration"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AtomType" eSuperTypes="#//ujf/verimag/bip/types/ComponentType">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="InternalDataSynchronizedWithExportedData checkForCyclesInPrioritiesInAtom checkUninitializedVariablesInAtomInternalDataDeclaration"/>
            </eAnnotations>
            <eOperations name="getInternalPortDeclaration" eType="#//ujf/verimag/bip/component/atom/AtomInternalPortDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getExternalPortDeclaration" eType="#//ujf/verimag/bip/component/atom/AtomExternalPortDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getInternalDataDeclaration" eType="#//ujf/verimag/bip/component/atom/AtomInternalDataDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getClockDeclaration" eType="#//ujf/verimag/bip/time/ClockDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getPriorityDeclaration" eType="#//ujf/verimag/bip/priority/AtomPriorityDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getInvariantDeclaration" eType="#//ujf/verimag/bip/invariant/AtomInvariant">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="internalPortDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/atom/AtomInternalPortDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="externalPortDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/atom/AtomExternalPortDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" lowerBound="1"
                eType="#//ujf/verimag/bip/behavior/PetriNet" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="internalDataDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/atom/AtomInternalDataDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="clockDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/time/ClockDeclaration" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportPortDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/atom/AtomExportPortDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="priorities" upperBound="-1"
                eType="#//ujf/verimag/bip/priority/AtomPriorityDeclaration" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" upperBound="-1"
                eType="#//ujf/verimag/bip/invariant/AtomInvariant" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CompoundType" eSuperTypes="#//ujf/verimag/bip/types/ComponentType">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="exportedPortsListsSynchronized exportedDataListsSynchronized checkForCyclesInPrioritiesInCompound&#xA;"/>
            </eAnnotations>
            <eOperations name="getComponentDeclaration" eType="#//ujf/verimag/bip/component/ComponentDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getConnectorDeclaration" eType="#//ujf/verimag/bip/connector/ConnectorDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getExportPortDeclaration" eType="#//ujf/verimag/bip/component/compound/CompoundExportPortDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getExportDataDeclaration" eType="#//ujf/verimag/bip/component/compound/CompoundExportDataDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getPriorityDeclaration" eType="#//ujf/verimag/bip/priority/CompoundPriorityDeclaration">
              <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="componentDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/ComponentDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="connectorDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/connector/ConnectorDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportPortDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/compound/CompoundExportPortDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportDataDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/component/compound/CompoundExportDataDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="priorities" upperBound="-1"
                eType="#//ujf/verimag/bip/priority/CompoundPriorityDeclaration" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorType" eSuperTypes="#//ujf/verimag/bip/types/BipType">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="interactionDefinedIfExportPortWithData noDuplicatedInteractionAction checkDownWhenNoDataInConnectorPort missingInteractionIfExportPortWithData checkUninitializedVariablesInConnectorDataDeclaration"/>
            </eAnnotations>
            <eOperations name="getDataDeclaration" eType="#//ujf/verimag/bip/connector/ConnectorDataDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getPortParameterDeclaration" eType="#//ujf/verimag/bip/connector/ConnectorPortParameterDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="isDefined" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
              <eParameters name="ports" ordered="false" unique="false" upperBound="-1"
                  eType="#//ujf/verimag/bip/connector/ConnectorPortParameterDeclaration"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportedPortDeclaration"
                eType="#//ujf/verimag/bip/connector/ConnectorExportedPortDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/connector/ConnectorDataDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
                eType="#//ujf/verimag/bip/connector/ConnectorInteractionAction" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="interactionDefinition"
                lowerBound="1" eType="#//ujf/verimag/bip/connector/ConnectorInteractionDefinition"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/connector/ConnectorPortParameterDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="asyncResume" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
                defaultValueLiteral="false"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PortType" eSuperTypes="#//ujf/verimag/bip/types/BipType">
            <eOperations name="getDataParameterDeclaration" eType="#//ujf/verimag/bip/port/PortDataParameterDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataParameterDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/port/PortDataParameterDeclaration"
                containment="true"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="data" nsURI="http://bip2/ujf/verimag/bip/data/1.0" nsPrefix="bip2.ujf.verimag.bip.data">
          <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//ujf/verimag/bip/types/Type">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="backendName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DataDeclaration" abstract="true"
              interface="true" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
                eType="#//ujf/verimag/bip/data/DataType"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ujf/verimag/bip/actionlang/ValuedExpression"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ExplicitDataDeclaration" abstract="true"
              interface="true" eSuperTypes="#//ujf/verimag/bip/data/DataDeclaration">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasInitializationIfConst"/>
            </eAnnotations>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SubDataDeclarationReference">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasOneDeclaration"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="forwardDataDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="componentDeclaration"
                eType="#//ujf/verimag/bip/component/ComponentDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="portDeclaration"
                eType="#//ujf/verimag/bip/port/PortDeclaration"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DataParameter" abstract="true"
              interface="true">
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="#//ujf/verimag/bip/data/DataType"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DataDeclarationReferenceDataParameter"
              eSuperTypes="#//ujf/verimag/bip/data/DataParameter">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasCorrectType hasCorrectConst"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataDeclarationReference"
                lowerBound="1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="port" nsURI="http://bip2/ujf/verimag/bip/port/1.0" nsPrefix="bip2.ujf.verimag.bip.port">
          <eClassifiers xsi:type="ecore:EClass" name="PortDeclaration" abstract="true"
              interface="true">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasCorrectNumberOfDataParameters"/>
            </eAnnotations>
            <eOperations name="getDataParameter" eType="#//ujf/verimag/bip/data/DataDeclarationReferenceDataParameter">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="portType" lowerBound="1"
                eType="#//ujf/verimag/bip/types/PortType"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataParameters"
                upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclarationReferenceDataParameter"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SubPortDeclarationReference">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="subPortDeclarationReferenceHasOneDeclaration"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="forwardPortDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/port/PortDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="componentDeclaration"
                eType="#//ujf/verimag/bip/component/ComponentDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="connectorDeclaration"
                eType="#//ujf/verimag/bip/connector/ConnectorDeclaration"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PortDataParameterDeclaration"
              eSuperTypes="#//ujf/verimag/bip/data/DataDeclaration"/>
          <eClassifiers xsi:type="ecore:EClass" name="PortDeclarationReferenceParameter">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="portParameterHasCorrectPortType"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/port/PortDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subPortDeclarationReference"
                lowerBound="1" eType="#//ujf/verimag/bip/port/SubPortDeclarationReference"
                containment="true"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="behavior" nsURI="http://bip2/ujf/verimag/bip/behavior/1.0"
            nsPrefix="bip2.ujf.verimag.bip.behavior">
          <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="checkIllFormed checkUninitializedVariablesOfPetriNet checkUninitializedVariablesExportedByPortOfAtom checkUninitializedVariablesExportedAtom"/>
            </eAnnotations>
            <eOperations name="getState" eType="#//ujf/verimag/bip/behavior/State">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="isOneSafe" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
              <eParameters name="state" lowerBound="1" eType="#//ujf/verimag/bip/behavior/State"/>
            </eOperations>
            <eOperations name="mayBeOneSafe" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
              <eParameters name="state" lowerBound="1" eType="#//ujf/verimag/bip/behavior/State"/>
            </eOperations>
            <eOperations name="isCoverable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
              <eParameters name="states" ordered="false" unique="false" upperBound="-1"
                  eType="#//ujf/verimag/bip/behavior/State"/>
            </eOperations>
            <eOperations name="mayBeCoverable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
              <eParameters name="states" ordered="false" unique="false" upperBound="-1"
                  eType="#//ujf/verimag/bip/behavior/State"/>
            </eOperations>
            <eOperations name="getUninitializedVariables" upperBound="-1" eType="#//ujf/verimag/bip/actionlang/Expression"/>
            <eOperations name="getUninitializedExportedVariables" ordered="false"
                upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eOperations name="getUninitializedExportedVariables" ordered="false"
                upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration">
              <eParameters name="transition" lowerBound="1" eType="#//ujf/verimag/bip/behavior/Transition"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/behavior/State" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="initStates" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/behavior/State"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
                eType="#//ujf/verimag/bip/behavior/Transition" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="initialActions"
                upperBound="-1" eType="#//ujf/verimag/bip/actionlang/Expression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="initialResume"
                eType="#//ujf/verimag/bip/time/Resume" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="State">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement #//ujf/verimag/bip/time/Guarded #//ujf/verimag/bip/time/Resumed #//ujf/verimag/bip/time/UrgentElement">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasNoVariableModifiedBetweenProvidedAndDo"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/behavior/State"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="destinations" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/behavior/State"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="triggerPort" eType="#//ujf/verimag/bip/component/atom/AtomInternalExternalPortDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
                eType="#//ujf/verimag/bip/actionlang/Expression" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="InternalTransition" eSuperTypes="#//ujf/verimag/bip/behavior/Transition #//ujf/verimag/bip/time/GuardedUntimed">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="internalTransitionHasNoTriggerPort"/>
            </eAnnotations>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="priority" nsURI="http://bip2/ujf/verimag/bip/priority/1.0"
            nsPrefix="bip2.ujf.verimag.bip.priority">
          <eClassifiers xsi:type="ecore:EClass" name="CompoundPriorityDeclaration"
              eSuperTypes="#//ujf/verimag/bip/time/Guarded #//ujf/verimag/bip/time/GuardedUntimed">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="compoundPriorityHasAtMostOneWildcard compoundPriorityInvolvesOnlyTopLevelConnectors priorityDuplicateMaximalProgress"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="low" eType="#//ujf/verimag/bip/priority/ConnectorInteraction"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="high" eType="#//ujf/verimag/bip/priority/ConnectorInteraction"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorInteraction">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="portReferencesOnCorrectConnectorDeclaration noDuplicatedPortReferenceInConnectorInteraction interactionIsDefinedInConnector&#xA;"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="connectorDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/connector/ConnectorDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="portDeclarationReferences"
                upperBound="-1" eType="#//ujf/verimag/bip/port/SubPortDeclarationReference"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AtomPriorityDeclaration" eSuperTypes="#//ujf/verimag/bip/time/Guarded #//ujf/verimag/bip/time/GuardedUntimed">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="atomPriorityHasAtMostOneWildcard"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="low" eType="#//ujf/verimag/bip/component/atom/AtomInternalPortDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="high" eType="#//ujf/verimag/bip/component/atom/AtomInternalPortDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="connector" nsURI="http://bip2/ujf/verimag/bip/connector/1.0"
            nsPrefix="bip2.ujf.verimag.bip.connector">
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorDeclaration" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasCorrectNumberOfPortParameters connectorDeclarationHasnoDuplicatedPortReferenceParameter connectorHasExportPortBound"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="#//ujf/verimag/bip/types/ConnectorType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="portParameters"
                upperBound="-1" eType="#//ujf/verimag/bip/port/PortDeclarationReferenceParameter"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorPortParameterDeclaration"
              eSuperTypes="#//ujf/verimag/bip/port/PortDeclaration"/>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorExportedPortDeclaration"
              eSuperTypes="#//ujf/verimag/bip/port/PortDeclaration #//ujf/verimag/bip/annotation/AnnotatedElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorDataDeclaration" eSuperTypes="#//ujf/verimag/bip/data/ExplicitDataDeclaration"/>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorInteractionAction"
              eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement #//ujf/verimag/bip/time/Guarded">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="onPortInConnectorParameters upDoesNotContainExternalSubDataRefOnLHSAssignments connectorActionNotEmpty noUpIfNoExportedPort triggerPortsValidWrtDefine missingUpForExportedPort hasNoVariableModifiedBetweenUpAndDown checkUninitializedVariablesOfConnectorInteractionAction checkUninitializedVariablesExportedByPortOfConnector"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="onPorts" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/connector/ConnectorPortParameterDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="up" upperBound="-1"
                eType="#//ujf/verimag/bip/actionlang/Expression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="down" upperBound="-1"
                eType="#//ujf/verimag/bip/actionlang/Expression" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorInteractionDefinition">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="quoted" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorInteractionPortReference"
              eSuperTypes="#//ujf/verimag/bip/connector/ConnectorInteractionDefinition">
            <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
                eType="#//ujf/verimag/bip/connector/ConnectorPortParameterDeclaration"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorInteractionNestedDefinition"
              eSuperTypes="#//ujf/verimag/bip/connector/ConnectorInteractionDefinition">
            <eStructuralFeatures xsi:type="ecore:EReference" name="subInteractions"
                lowerBound="1" upperBound="-1" eType="#//ujf/verimag/bip/connector/ConnectorInteractionDefinition"
                containment="true"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="component" nsURI="http://bip2/ujf/verimag/bip/component/1.0"
            nsPrefix="bip2.ujf.verimag.bip.component">
          <eClassifiers xsi:type="ecore:EClass" name="ComponentDeclaration" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="componentDeclarationHasCorrectNumberOfParam componentDeclarationHasNoUnconnectedPort"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="#//ujf/verimag/bip/types/ComponentType"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ComponentDataParameterDeclaration"
              eSuperTypes="#//ujf/verimag/bip/data/DataDeclaration">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="dataTypeIsBasic"/>
            </eAnnotations>
          </eClassifiers>
          <eSubpackages name="atom" nsURI="http://bip2/ujf/verimag/bip/component/atom/1.0"
              nsPrefix="bip2.ujf.verimag.bip.component.atom">
            <eClassifiers xsi:type="ecore:EClass" name="AtomInternalExternalPortDeclaration"
                abstract="true" interface="true" eSuperTypes="#//ujf/verimag/bip/port/PortDeclaration #//ujf/verimag/bip/annotation/AnnotatedElement"/>
            <eClassifiers xsi:type="ecore:EClass" name="AtomInternalPortDeclaration"
                eSuperTypes="#//ujf/verimag/bip/component/atom/AtomInternalExternalPortDeclaration"/>
            <eClassifiers xsi:type="ecore:EClass" name="AtomExternalPortDeclaration"
                eSuperTypes="#//ujf/verimag/bip/component/atom/AtomInternalExternalPortDeclaration">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="backendName"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="policy" lowerBound="1"
                  eType="#//ujf/verimag/bip/component/atom/EventConsumptionPolicy"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="AtomInternalDataDeclaration"
                eSuperTypes="#//ujf/verimag/bip/data/ExplicitDataDeclaration">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="exported" lowerBound="1"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="AtomExportPortDeclaration"
                eSuperTypes="#//ujf/verimag/bip/port/PortDeclaration #//ujf/verimag/bip/annotation/AnnotatedElement">
              <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
                <details key="constraints" value="referencedPortsHaveTheSameType noDuplicatedPortReference"/>
              </eAnnotations>
              <eStructuralFeatures xsi:type="ecore:EReference" name="portDeclarationReferences"
                  lowerBound="1" upperBound="-1" eType="#//ujf/verimag/bip/component/atom/AtomInternalPortDeclaration"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EEnum" name="EventConsumptionPolicy">
              <eLiterals name="remember"/>
              <eLiterals name="ignore" value="1"/>
              <eLiterals name="error" value="2" literal="error"/>
            </eClassifiers>
          </eSubpackages>
          <eSubpackages name="compound" nsURI="http://bip2/ujf/verimag/bip/component/compound/1.0"
              nsPrefix="bip2.ujf.verimag.bip.component.compound">
            <eClassifiers xsi:type="ecore:EClass" name="CompoundExportPortDeclaration"
                eSuperTypes="#//ujf/verimag/bip/port/PortDeclaration #//ujf/verimag/bip/annotation/AnnotatedElement">
              <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
                <details key="constraints" value="referencedPortsHaveTheSameType noDuplicatedPortReference"/>
              </eAnnotations>
              <eStructuralFeatures xsi:type="ecore:EReference" name="portDeclarationReferences"
                  lowerBound="1" upperBound="-1" eType="#//ujf/verimag/bip/port/SubPortDeclarationReference"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="CompoundExportDataDeclaration"
                eSuperTypes="#//ujf/verimag/bip/data/DataDeclaration #//ujf/verimag/bip/annotation/AnnotatedElement">
              <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
                <details key="constraints" value="sameDataTypeAsPointedDeclaration"/>
              </eAnnotations>
              <eStructuralFeatures xsi:type="ecore:EReference" name="dataDeclarationReference"
                  lowerBound="1" eType="#//ujf/verimag/bip/data/SubDataDeclarationReference"
                  containment="true"/>
            </eClassifiers>
          </eSubpackages>
        </eSubpackages>
        <eSubpackages name="packaging" nsURI="http://bip2/ujf/verimag/bip/package/1.0"
            nsPrefix="bip2.ujf.verimag.bip.package">
          <eClassifiers xsi:type="ecore:EClass" name="BipPackage" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="checkForCyclesInSubTyping"/>
            </eAnnotations>
            <eOperations name="getAtomType" eType="#//ujf/verimag/bip/types/AtomType">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getCompoundType" eType="#//ujf/verimag/bip/types/CompoundType">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getConnectorType" eType="#//ujf/verimag/bip/types/ConnectorType">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getPortType" eType="#//ujf/verimag/bip/types/PortType">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getDataType" eType="#//ujf/verimag/bip/data/DataType">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getConstDataDeclaration" eType="#//ujf/verimag/bip/packaging/ConstDataDeclaration">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getFunctionCallPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/FunctionCallPrototype">
              <eParameters name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getFunctionCallPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/FunctionCallPrototype">
              <eParameters name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eParameters name="parametersTypes" unique="false" upperBound="-1" eType="#//ujf/verimag/bip/types/Type"/>
            </eOperations>
            <eOperations name="getBinaryOpPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/BinaryOpPrototype">
              <eParameters name="operator" eType="#//ujf/verimag/bip/actionlang/BinaryOperators"/>
            </eOperations>
            <eOperations name="getBinaryOpPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/BinaryOpPrototype">
              <eParameters name="operator" eType="#//ujf/verimag/bip/actionlang/BinaryOperators"/>
              <eParameters name="parametersTypes" unique="false" upperBound="-1" eType="#//ujf/verimag/bip/types/Type"/>
            </eOperations>
            <eOperations name="getUnaryOpPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/UnaryOpPrototype">
              <eParameters name="operator" eType="#//ujf/verimag/bip/actionlang/UnaryOperators"/>
            </eOperations>
            <eOperations name="getUnaryOpPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/UnaryOpPrototype">
              <eParameters name="operator" eType="#//ujf/verimag/bip/actionlang/UnaryOperators"/>
              <eParameters name="parametersTypes" unique="false" upperBound="-1" eType="#//ujf/verimag/bip/types/Type"/>
            </eOperations>
            <eOperations name="getBoolDataType" lowerBound="1" eType="#//ujf/verimag/bip/data/DataType"/>
            <eOperations name="getIntDataType" lowerBound="1" eType="#//ujf/verimag/bip/data/DataType"/>
            <eOperations name="getFloatDataType" lowerBound="1" eType="#//ujf/verimag/bip/data/DataType"/>
            <eOperations name="getStringDataType" lowerBound="1" eType="#//ujf/verimag/bip/data/DataType"/>
            <eOperations name="getNanosecondType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eOperations name="getMicrosecondType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eOperations name="getMillisecondType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eOperations name="getSecondType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eOperations name="getMinuteType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eOperations name="getHourType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eOperations name="getDayType" lowerBound="1" eType="#//ujf/verimag/bip/time/Time"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="atomTypes" upperBound="-1"
                eType="#//ujf/verimag/bip/types/AtomType" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="compoundTypes"
                upperBound="-1" eType="#//ujf/verimag/bip/types/CompoundType" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="connectorTypes"
                upperBound="-1" eType="#//ujf/verimag/bip/types/ConnectorType" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="portTypes" upperBound="-1"
                eType="#//ujf/verimag/bip/types/PortType" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
                eType="#//ujf/verimag/bip/data/DataType" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="used_packages"
                upperBound="-1" eType="#//ujf/verimag/bip/packaging/BipPackage"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="constData" upperBound="-1"
                eType="#//ujf/verimag/bip/packaging/ConstDataDeclaration" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="prototypes" upperBound="-1"
                eType="#//ujf/verimag/bip/packaging/Prototype" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BipPackageSet">
            <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
                eType="#//ujf/verimag/bip/packaging/BipPackage"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConstDataDeclaration" eSuperTypes="#//ujf/verimag/bip/data/ExplicitDataDeclaration">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasCorrectConst"/>
            </eAnnotations>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Prototype" abstract="true" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="involveOnlyDataTypeIfNotNative"/>
            </eAnnotations>
            <eOperations name="isBetterMatchingThan" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
              <eParameters name="types" unique="false" upperBound="-1" eType="#//ujf/verimag/bip/types/Type"/>
              <eParameters name="prototype" lowerBound="1" eType="#//ujf/verimag/bip/packaging/Prototype"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDeclarations"
                upperBound="-1" eType="#//ujf/verimag/bip/packaging/PrototypeParameterDeclaration"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//ujf/verimag/bip/types/Type"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="native" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="FunctionCallPrototype" eSuperTypes="#//ujf/verimag/bip/packaging/Prototype">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BinaryOpPrototype" eSuperTypes="#//ujf/verimag/bip/packaging/Prototype">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/BinaryOperators"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="UnaryOpPrototype" eSuperTypes="#//ujf/verimag/bip/packaging/Prototype">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/UnaryOperators"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PrototypeParameterDeclaration">
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="#//ujf/verimag/bip/types/Type"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="actionlang" nsURI="http://bip2/ujf/verimag/bip/actionlang/1.0"
            nsPrefix="bip2.ujf.verimag.bip.actionlang">
          <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperators">
            <eLiterals name="addition" literal="+"/>
            <eLiterals name="subtraction" value="1" literal="-"/>
            <eLiterals name="multiplication" value="2" literal="*"/>
            <eLiterals name="bwise_and" value="3" literal="&amp;"/>
            <eLiterals name="bwise_xor" value="4" literal="^"/>
            <eLiterals name="bwise_or" value="5" literal="|"/>
            <eLiterals name="logical_and" value="6" literal="&amp;&amp;"/>
            <eLiterals name="logical_or" value="7" literal="||"/>
            <eLiterals name="equal" value="8" literal="=="/>
            <eLiterals name="not_equal" value="9" literal="!="/>
            <eLiterals name="less_than" value="10" literal="&lt;"/>
            <eLiterals name="greater_than" value="11" literal=">"/>
            <eLiterals name="less_than_or_equal" value="12" literal="&lt;="/>
            <eLiterals name="greater_than_or_equal" value="13" literal=">="/>
            <eLiterals name="division" value="14" literal="/"/>
            <eLiterals name="modulo" value="15" literal="%"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperators">
            <eLiterals name="plus" literal="+"/>
            <eLiterals name="minus" value="1" literal="-"/>
            <eLiterals name="logical_not" value="2" literal="!"/>
            <eLiterals name="bwise_not" value="3" literal="~"/>
            <eLiterals name="quote" value="4" literal="'"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BinaryOpExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasOneMatchingPrototype"/>
            </eAnnotations>
            <eOperations name="getPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/BinaryOpPrototype"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/BinaryOperators"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="UnaryOpExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasOneMatchingPrototype"/>
            </eAnnotations>
            <eOperations name="getPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/UnaryOpPrototype"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/UnaryOperators"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ValuedExpression" abstract="true"
              eSuperTypes="#//ujf/verimag/bip/actionlang/Expression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasCorrectType hasCorrectConst noSideEffectInGuards"/>
            </eAnnotations>
            <eOperations name="getType" eType="#//ujf/verimag/bip/types/Type"/>
            <eOperations name="getExpectedType" eType="#//ujf/verimag/bip/types/Type"/>
            <eOperations name="isConst" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eOperations name="expectedIsConst" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eOperations name="isInConstantContext" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eOperations name="hasSideEffect" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SubDataDeclarationReferenceExpression"
              eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="dataIsExportedInComponent dataRefInConnectorActionToInvolvedPort"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subDataDeclarationRef"
                lowerBound="1" eType="#//ujf/verimag/bip/data/SubDataDeclarationReference"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DirectDataDeclarationReferenceExpression"
              eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AssignmentExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/Expression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="rhsIsADataDeclarationReference hasCorrectConst"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//ujf/verimag/bip/actionlang/ValuedExpression"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="FunctionCallExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="hasOneMatchingPrototype hasValueInValuedContext"/>
            </eAnnotations>
            <eOperations name="getPrototypes" upperBound="-1" eType="#//ujf/verimag/bip/packaging/FunctionCallPrototype"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"
              interface="true">
            <eOperations name="getReadVariables" upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eOperations name="getMayReadVariables" upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eOperations name="getWriteVariables" upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eOperations name="getMayWriteVariables" upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eOperations name="getMayReadUninitializedVariables" upperBound="-1" eType="#//ujf/verimag/bip/actionlang/Expression">
              <eParameters name="uninitialized" ordered="false" upperBound="-1" eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            </eOperations>
            <eOperations name="getReadClocks" upperBound="-1" eType="#//ujf/verimag/bip/time/ClockDeclaration"/>
            <eOperations name="getMayReadClocks" upperBound="-1" eType="#//ujf/verimag/bip/time/ClockDeclaration"/>
            <eOperations name="getWriteClocks" upperBound="-1" eType="#//ujf/verimag/bip/time/ClockDeclaration"/>
            <eOperations name="getMayWriteClocks" upperBound="-1" eType="#//ujf/verimag/bip/time/ClockDeclaration"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ValuedReferenceExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eStructuralFeatures xsi:type="ecore:EReference" name="expressionReference"
                lowerBound="1" eType="#//ujf/verimag/bip/actionlang/ValuedExpression"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DirectBooleanExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="IfThenElseExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/Expression">
            <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
                eType="#//ujf/verimag/bip/actionlang/ValuedExpression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1"
                upperBound="-1" eType="#//ujf/verimag/bip/actionlang/Expression" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="else" upperBound="-1"
                eType="#//ujf/verimag/bip/actionlang/Expression" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DirectIntegerExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DirectFloatExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DirectStringExpression" eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DirectClockDeclarationReferenceExpression"
              eSuperTypes="#//ujf/verimag/bip/actionlang/ValuedExpression">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="invalidUseOfClocksInDo"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="clockDeclaration"
                lowerBound="1" eType="#//ujf/verimag/bip/time/ClockDeclaration"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="instance" nsURI="http://bip2/ujf/verimag/bip/instance/1.0"
            nsPrefix="bip2.ujf.verimag.bip.instance">
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorInstance">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="connectorDoesNotBindTheSameComponentMoreThanOnce"/>
            </eAnnotations>
            <eOperations name="getDataInstance" eType="#//ujf/verimag/bip/instance/DataInstance">
              <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
                eType="#//ujf/verimag/bip/connector/ConnectorDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subDataInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/DataInstance" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="portParamInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/PortInstance"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportedPort" eType="#//ujf/verimag/bip/instance/ConnectorPortInstance"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="DataInstance">
            <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
                eType="#//ujf/verimag/bip/data/DataDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="proxyLink" eType="#//ujf/verimag/bip/instance/DataInstance"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CompoundPriorityInstance">
            <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
                eType="#//ujf/verimag/bip/priority/CompoundPriorityDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="lowConnector" eType="#//ujf/verimag/bip/instance/ConnectorInstance"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="highConnector"
                eType="#//ujf/verimag/bip/instance/ConnectorInstance"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="lowPorts" upperBound="-1"
                eType="#//ujf/verimag/bip/instance/PortInstance"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="highPorts" upperBound="-1"
                eType="#//ujf/verimag/bip/instance/PortInstance"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AtomInstance" eSuperTypes="#//ujf/verimag/bip/instance/ComponentInstance">
            <eOperations name="getInternalDataInstance" eType="#//ujf/verimag/bip/instance/DataInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getInternalPortInstance" eType="#//ujf/verimag/bip/instance/AtomInternalPortInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subDataInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/DataInstance" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="internalPorts"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/AtomInternalPortInstance"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="externalPorts"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/AtomExternalPortInstance"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CompoundInstance" eSuperTypes="#//ujf/verimag/bip/instance/ComponentInstance">
            <eOperations name="getComponentInstance" eType="#//ujf/verimag/bip/instance/ComponentInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getAtomInstance" eType="#//ujf/verimag/bip/instance/AtomInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getCompoundInstance" eType="#//ujf/verimag/bip/instance/CompoundInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getConnectorInstance" eType="#//ujf/verimag/bip/instance/ConnectorInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getCompoundPriorityInstance" eType="#//ujf/verimag/bip/instance/CompoundPriorityInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subPriorities"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/CompoundPriorityInstance"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subConnectorInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/ConnectorInstance"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subAtomInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/AtomInstance" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subCompoundInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/CompoundInstance"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="subDataInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/DataInstance" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" abstract="true"
              interface="true">
            <eOperations name="getPortInstance" eType="#//ujf/verimag/bip/instance/ExportedPortInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eOperations name="getDataInstance" eType="#//ujf/verimag/bip/instance/DataInstance">
              <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
                eType="#//ujf/verimag/bip/component/ComponentDeclaration"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="exportedPorts"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/ExportedPortInstance"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PortInstance" abstract="true"
              interface="true">
            <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
                eType="#//ujf/verimag/bip/port/PortDeclaration"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ExportedPortInstance" eSuperTypes="#//ujf/verimag/bip/instance/PortInstance">
            <eStructuralFeatures xsi:type="ecore:EReference" name="referencedPorts"
                lowerBound="1" upperBound="-1" eType="#//ujf/verimag/bip/instance/PortInstance"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AtomInternalPortInstance" eSuperTypes="#//ujf/verimag/bip/instance/PortInstance">
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataParamInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/DataInstance"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AtomExternalPortInstance" eSuperTypes="#//ujf/verimag/bip/instance/PortInstance">
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataParamInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/DataInstance"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ConnectorPortInstance" eSuperTypes="#//ujf/verimag/bip/instance/PortInstance">
            <eStructuralFeatures xsi:type="ecore:EReference" name="dataParamInstances"
                upperBound="-1" eType="#//ujf/verimag/bip/instance/DataInstance"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="annotation" nsURI="http://bip2/ujf/verimag/bip/annotation/1.0"
            nsPrefix="bip2.ujf.verimag.bip.annotation">
          <eClassifiers xsi:type="ecore:EClass" name="AnnotatedElement" abstract="true">
            <eStructuralFeatures xsi:type="ecore:EReference" name="bipAnnotations"
                upperBound="-1" eType="#//ujf/verimag/bip/annotation/StringToAnnotationMapEntry"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="BipAnnotation">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
                eType="#//ujf/verimag/bip/annotation/StringToStringMapEntry" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="StringToAnnotationMapEntry"
              instanceClassName="java.util.Map$Entry">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
                eType="#//ujf/verimag/bip/annotation/BipAnnotation" containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="StringToStringMapEntry" instanceClassName="java.util.Map$Entry">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="invariant" nsURI="http://bip2/ujf/verimag/bip/invariant/1.0"
            nsPrefix="bip2.ujf.verimag.bip.invariant">
          <eClassifiers xsi:type="ecore:EClass" name="Invariant" abstract="true" interface="true"
              eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement #//ujf/verimag/bip/time/Guarded">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
                iD="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="AtomInvariant" eSuperTypes="#//ujf/verimag/bip/invariant/Invariant">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="fakeConstraint"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="exactState" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
                eType="#//ujf/verimag/bip/behavior/State"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="time" nsURI="http://bip2/ujf/verimag/bip/time/1.0" nsPrefix="bip2.ujf.verimag.bip.time">
          <eClassifiers xsi:type="ecore:EEnum" name="Urgency">
            <eLiterals name="lazy"/>
            <eLiterals name="delayable" value="1"/>
            <eLiterals name="eager" value="2"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="ClockDeclaration" eSuperTypes="#//ujf/verimag/bip/annotation/AnnotatedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1"
                eType="#//ujf/verimag/bip/time/Time"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="UrgentElement" abstract="true"
              interface="true">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="urgency" lowerBound="1"
                eType="#//ujf/verimag/bip/time/Urgency"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Time" eSuperTypes="#//ujf/verimag/bip/types/Type"/>
          <eClassifiers xsi:type="ecore:EClass" name="Guarded" abstract="true" interface="true">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="nestedComparisonOnClocks clocksOnOneSideOfLogicalOr invalidNotEqualOnClocks noClocksInLogicalNot invalidUseOfMultiplicationOrDivisionOnClocks comparisonOfMoreThanTwoClocks comparisonOfClocksHavingWrongSign"/>
            </eAnnotations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//ujf/verimag/bip/actionlang/ValuedExpression"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="GuardedUntimed" eSuperTypes="#//ujf/verimag/bip/time/Guarded">
            <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
              <details key="constraints" value="noClocksInGuard"/>
            </eAnnotations>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Resumed">
            <eStructuralFeatures xsi:type="ecore:EReference" name="resume" eType="#//ujf/verimag/bip/time/Resume"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Resume" eSuperTypes="#//ujf/verimag/bip/time/Guarded"/>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
